version: '3.8'

services:
  exam-display:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
    # Optional: Uncomment to persist logs
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "10m"
    #     max-file: "3"
    # Optional: Uncomment for resource limits
    # deploy:
    #   resources:
    #     limits:
    #       memory: 256M
    #       cpus: '0.5'
    #     reservations:
    #       memory: 128M
    #       cpus: '0.25'
