version: '3.8'

services:
  exam-display:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: exam-display-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - exam-display-network

  # Optional: Nginx reverse proxy for production (commented out by default)
  # nginx:
  #   image: nginx:alpine
  #   container_name: exam-display-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro  # If you have SSL certificates
  #   depends_on:
  #     - exam-display
  #   restart: unless-stopped
  #   networks:
  #     - exam-display-network

networks:
  exam-display-network:
    driver: bridge