apiVersion: v1
kind: Service
metadata:
  name: exam-display-service
  labels:
    app: exam-display
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: exam-display
