apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-display
  labels:
    app: exam-display
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exam-display
  template:
    metadata:
      labels:
        app: exam-display
    spec:
      containers:
      - name: exam-display
        image: exam-display:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: exam-display-config
              key: NODE_ENV
        - name: NTP_SERVER
          valueFrom:
            configMapKeyRef:
              name: exam-display-config
              key: NTP_SERVER
        - name: TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: exam-display-config
              key: TIMEZONE
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
      securityContext:
        fsGroup: 1001
